# Generated by Django 3.0.2 on 2020-01-29 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingTitle', models.CharField(max_length=255)),
                ('MeetingDate', models.DateField()),
                ('MeetingTime', models.TimeField()),
                ('MeetingLocation', models.CharField(max_length=255)),
                ('Agenda', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourceName', models.CharField(max_length=255)),
                ('ResourceType', models.DateField()),
                ('ResourceURL', models.URLField(blank=True, null=True)),
                ('DateEntered', models.DateField()),
                ('Description', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'db_table': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinutesText', models.TextField()),
                ('Attendance', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('Meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project1.Meeting')),
            ],
            options={
                'verbose_name_plural': 'MeetingMinutes',
                'db_table': 'MeetingMinute',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventTitle', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Description', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'Event',
            },
        ),
    ]
